
import type { Template } from '../types';

export const TEMPLATE_LIBRARY: Template[] = [
  {
    id: 'studio-01',
    title: 'Clean Studio Backdrop',
    description: 'A classic, professional product shot on a clean, seamless background.',
    category: 'Studio',
    previewImageUrl: 'https://storage.googleapis.com/genius-images-ny/images/ChatGPT%20Image%20May%2023%2C%202025%2C%2002_16_29%20PM.png',
    promptTemplate: "A professional studio product shot of {{PRODUCT_NAME}} on a solid, light grey seamless background. Use clean, soft lighting to highlight the product's details. The style should be minimalist and elegant, perfect for an e-commerce website. The overall mood is {{BRAND_VIBE}}.",
    imageGenerationPrompt: "Professional product photography of a sleek, modern water bottle made of matte black stainless steel. The bottle is centered on a seamless, solid, light grey background (#f0f0f0). The scene is lit with clean, soft studio lighting that creates gentle highlights and minimizes shadows, emphasizing the bottle's form and texture. Style: minimalist, elegant, commercial. Shot on a DSLR with a prime lens.",
    type: 'image',
    animationPrompt: 'Slow cinematic pan around the product, emphasizing the lighting.',
  },
  {
    id: 'studio-02',
    title: 'Geometric Pedestals',
    description: 'Showcase your product on modern geometric shapes for a bold, contemporary look.',
    category: 'Studio',
    previewImageUrl: 'https://storage.googleapis.com/genius-images-ny/images/ChatGPT%20Image%20May%2023%2C%202025%2C%2012_48_45%20PM.png',
    promptTemplate: 'A high-fashion product shot of {{PRODUCT_NAME}} displayed on a set of overlapping pastel-colored geometric pedestals and blocks. The lighting should be bright and direct, creating sharp shadows. The background is a solid, complementary color. The feel is modern, artistic, and {{BRAND_VIBE}}.',
    imageGenerationPrompt: 'A stylish advertisement for a luxury watch. The watch is displayed on a mint green geometric pedestal. The scene includes other geometric shapes in pastel pink and cream. The background is a solid soft beige. The lighting is bright and direct, creating crisp, defined shadows. The style is modern, minimalist, and high-fashion. 4k, photorealistic.',
    type: 'image',
    animationPrompt: 'Subtle floating motion of the geometric shapes.',
  },
  {
    id: 'lifestyle-01',
    title: 'Cozy Morning Coffee',
    description: 'Place your product in a warm, inviting morning scene.',
    category: 'Lifestyle',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Morning+Coffee',
    promptTemplate: 'A lifestyle photograph of {{PRODUCT_NAME}} on a wooden coffee table next to a steaming mug of coffee and an open book. Soft morning light streams in through a nearby window, creating a warm and inviting atmosphere. The scene should feel relatable and cozy, targeting {{TARGET_AUDIENCE}}.',
    imageGenerationPrompt: 'A cozy lifestyle scene featuring a pair of high-end, noise-cancelling headphones resting on a rustic wooden coffee table. Next to the headphones are a steaming ceramic mug of coffee and an open book with glasses. Soft, warm morning light streams through a window, illuminating the scene. The atmosphere is peaceful, comfortable, and inviting. Photorealistic, depth of field.',
    type: 'image',
    animationPrompt: 'Steam rising gently from the coffee mug, with dust motes dancing in the light.',
  },
  {
    id: 'lifestyle-02',
    title: 'On the Go',
    description: 'Feature your product in a dynamic, urban setting.',
    category: 'Lifestyle',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Urban+Setting',
    promptTemplate: 'Action shot of {{PRODUCT_NAME}} being used by a person in a bustling, stylish urban environment. The background is slightly blurred to emphasize the product. The overall image should feel energetic, modern, and aspirational, resonating with a {{TARGET_AUDIENCE}} lifestyle.',
    imageGenerationPrompt: 'A dynamic lifestyle shot of a stylish backpack in a modern urban setting. The backpack is worn by a person walking through a bustling city street, with blurred background motion of people and city lights. The image feels energetic, fashionable, and aspirational. The focus is sharp on the backpack, highlighting its textures and details. Cinematic, photorealistic.',
    type: 'image',
    animationPrompt: 'Motion blur of the background city street while the product stays in focus.',
  },
  {
    id: 'seasonal-01',
    title: 'Spring Bloom',
    description: 'Set your product among fresh spring flowers and soft light.',
    category: 'Seasonal',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Spring+Bloom',
    promptTemplate: 'A vibrant spring scene featuring {{PRODUCT_NAME}} surrounded by fresh cherry blossoms and tulips. The lighting is bright and airy, with a soft-focus background of a green garden. The mood is refreshing, clean, and optimistic, perfect for a {{BRAND_VIBE}} spring campaign.',
    imageGenerationPrompt: 'A bottle of perfume sitting on a white marble surface, surrounded by fresh, dewy cherry blossoms and pink tulips. The background is a soft-focus garden with lush greenery. The lighting is bright and airy, evoking a fresh spring morning. Style: elegant, clean, refreshing. Photorealistic, macro details.',
    activeMonths: [2, 3, 4], // March, April, May
    type: 'image',
    animationPrompt: 'Flower petals gently falling in the background.',
  },
  {
    id: 'seasonal-02',
    title: 'Summer Beach Day',
    description: 'A bright, sunny beach scene to give your product a vacation vibe.',
    category: 'Seasonal',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Beach+Day',
    promptTemplate: 'A vibrant, sun-drenched photo of {{PRODUCT_NAME}} on a clean, sandy beach. The background features turquoise ocean waves and a clear blue sky. The product is the hero, looking crisp and refreshing. The feel is energetic, fun, and perfectly captures the {{BRAND_VIBE}} of summer.',
    imageGenerationPrompt: 'A can of sparkling soda, dripping with condensation, sits partially buried in clean, white sand on a tropical beach. In the background, turquoise waves gently lap the shore under a bright, clear blue sky. The sun is high, casting a sharp, clean light. Style: vibrant, commercial, refreshing. Photorealistic, 8k.',
    activeMonths: [5, 6, 7], // June, July, August
    type: 'image',
    animationPrompt: 'Gentle ocean waves moving in the background.',
  },
  {
    id: 'seasonal-03',
    title: 'Autumn Harvest',
    description: 'Nestle your product among cozy autumn elements like pumpkins and leaves.',
    category: 'Seasonal',
    previewImageUrl: 'https://storage.googleapis.com/genius-images-ny/images/generated_image_0.png',
    promptTemplate: 'A festive, {{BRAND_VIBE}} flat-lay of {{PRODUCT_NAME}} surrounded by mini pumpkins, colorful autumn leaves, and a cozy knit sweater. The color palette should be warm, with oranges, reds, and browns. The lighting is soft and golden, like a crisp autumn afternoon.',
    imageGenerationPrompt: 'A beautiful autumn-themed flat-lay featuring a bottle of premium skincare serum. The bottle is centrally placed and surrounded by mini pumpkins, vibrant red and orange autumn leaves, a cinnamon stick, and a corner of a cozy, chunky-knit sweater. The background is dark wood. The lighting is soft and golden, creating a warm, festive mood. Top-down view, sharp focus, rich textures.',
    activeMonths: [8, 9, 10], // September, October, November
    type: 'image',
    animationPrompt: 'Leaves gently falling across the scene.',
  },
  {
    id: 'seasonal-04',
    title: 'Winter Wonderland',
    description: 'A magical winter scene perfect for holiday campaigns.',
    category: 'Seasonal',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Winter',
    promptTemplate: 'A magical shot of {{PRODUCT_NAME}} resting on a bed of fresh, sparkling snow, with out-of-focus fairy lights in the background. A single, delicate snowflake is captured landing nearby. The mood is enchanting, festive, and perfect for a holiday gift guide targeting {{TARGET_AUDIENCE}}.',
    imageGenerationPrompt: 'An enchanting product shot of a luxury candle in a glass jar, resting on a bed of pristine, sparkling snow. The background is a soft-focus view of a winter forest at dusk with warm, glowing fairy lights (bokeh effect). A single, perfect snowflake is captured in mid-air near the candle. The mood is magical, festive, and serene. Cinematic, high detail.',
    activeMonths: [11, 0, 1], // December, January, February
    type: 'image',
    animationPrompt: 'Snow falling softly with twinkling lights in the background.',
  },
  {
    id: 'upcoming-01',
    title: 'Valentine\'s Romance',
    description: 'A romantic, elegant setting with roses and soft lighting.',
    category: 'Holidays & Events',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Valentine%27s',
    promptTemplate: 'An elegant, romantic scene for {{PRODUCT_NAME}}. The product is artfully placed among red rose petals and silk fabric. The lighting is soft and warm, with a few candles creating a gentle glow in the background. The mood is luxurious and perfect for a Valentine\'s Day gift.',
    imageGenerationPrompt: 'A bottle of expensive perfume is elegantly placed on a draped, deep red silk fabric, surrounded by fresh rose petals. In the background, soft-focus candles provide a warm, intimate glow. The scene is luxurious, romantic, and sophisticated. Photorealistic, shallow depth of field.',
    activeMonths: [1], // February
    type: 'image',
    animationPrompt: 'Candlelight flickering gently.',
  },
   {
    id: 'upcoming-02',
    title: 'Mother\'s Day Elegance',
    description: 'A bright, clean, and elegant scene with fresh flowers.',
    category: 'Holidays & Events',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Mother%27s+Day',
    promptTemplate: 'A beautiful and elegant flat-lay for {{PRODUCT_NAME}}, perfect for Mother\'s Day. The product is surrounded by a bouquet of fresh peonies and a handwritten card. The background is clean white marble. The lighting is bright and natural, creating a feeling of appreciation and love.',
    imageGenerationPrompt: 'An elegant Mother\'s Day flat-lay. A beautifully packaged box of chocolates is placed on a white marble surface, surrounded by a bouquet of fresh pink peonies and a handwritten card that says "Thank You". The lighting is bright, soft, and natural. The style is clean, sophisticated, and heartfelt.',
    activeMonths: [4], // May
    type: 'image',
    animationPrompt: 'Soft sunlight shifting across the flowers.',
  },
  {
    id: 'upcoming-03',
    title: 'Spooky Halloween',
    description: 'A fun and spooky setup with a dark, moody atmosphere.',
    category: 'Holidays & Events',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Halloween',
    promptTemplate: 'A moody and atmospheric Halloween shot of {{PRODUCT_NAME}}. The product sits on a dark wooden surface, surrounded by theatrical smoke, small black bats, and a hint of spiderwebs. The lighting is dramatic and orange, perhaps from a nearby jack-o\'-lantern. The mood is spooky, fun, and {{BRAND_VIBE}}.',
    imageGenerationPrompt: 'A pair of black leather boots on a dark, rustic wooden table. The scene is filled with theatrical fog, and a few small, decorative bats are in the background. A carved jack-o\'-lantern off-camera casts a dramatic, orange light on the boots. The mood is spooky, atmospheric, and stylish. Cinematic lighting, halloween theme.',
    activeMonths: [9], // October
    type: 'image',
    animationPrompt: 'Fog swirling ominously around the product.',
  },
  {
    id: 'upcoming-04',
    title: 'Holiday Cheer',
    description: 'A festive scene with ornaments, pine, and twinkling lights.',
    category: 'Holidays & Events',
    previewImageUrl: 'https://storage.googleapis.com/genius-images-ny/images/generated_image_0%20%282%29.png',
    promptTemplate: 'A festive holiday photograph of {{PRODUCT_NAME}} nestled among pine branches, red berries, and shiny ornaments. Twinkling holiday lights are softly blurred in the background. The scene is warm, joyful, and captures the magic of the holiday season, making it a perfect gift.',
    imageGenerationPrompt: 'A high-end leather wallet is nestled amongst fresh pine branches, clusters of red berries, and gold and silver christmas ornaments. In the background, warm twinkling holiday lights are beautifully blurred (bokeh). The overall mood is festive, warm, and luxurious. The perfect holiday gift. Photorealistic, tack sharp focus on the wallet.',
    activeMonths: [10, 11], // November, December
    type: 'image',
    animationPrompt: 'Twinkling holiday lights in the background.',
  },
  {
    id: 'surreal-01',
    title: 'Floating in Air',
    description: 'A gravity-defying, dreamlike presentation of your product.',
    category: 'Surreal',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Surreal',
    promptTemplate: 'A surreal, artistic image where {{PRODUCT_NAME}} is floating gracefully in the center of a room with clouds drifting by. The lighting is ethereal and dreamlike. The color palette is soft and pastel. This is a high-concept ad that feels {{BRAND_VIBE}} and artistic.',
    imageGenerationPrompt: 'A surreal and artistic advertisement where a pair of elegant, high-tech sneakers are floating weightlessly in the center of a minimalist room. Fluffy white clouds drift slowly through the room. The walls are a soft pastel blue. The lighting is ethereal and dreamlike, casting soft shadows. The overall mood is serene, imaginative, and high-concept. Photorealistic, 8k.',
    type: 'image',
    animationPrompt: 'The product floating gently with clouds drifting by.',
  },
  {
    id: 'surreal-02',
    title: 'Nature Fusion',
    description: 'Merge your product with natural elements for a stunning, organic visual.',
    category: 'Surreal',
    previewImageUrl: 'https://placehold.co/800x800/E2E8F0/31343C?text=Nature+Fusion',
    promptTemplate: 'An advertisement showcasing {{PRODUCT_NAME}} as if it is growing organically from a mossy patch of forest floor. Beautiful, bioluminescent flowers are intertwined with the product. The scene is at twilight, with magical lighting. Key selling points to hint at are: {{KEY_SELLING_POINTS}}.',
    imageGenerationPrompt: 'An organic, surreal product shot. A bottle of natural face oil appears to be growing from a patch of lush, green moss on a forest floor. Small, glowing, bioluminescent mushrooms and delicate flowers are intertwined around the base of the bottle. The scene is set at twilight, with magical, soft light filtering through the trees. The mood is enchanting and highlights the product\'s natural ingredients. Macro photography, fantasy style.',
    type: 'image',
    animationPrompt: 'Glowing plants pulsing gently with light.',
  },
  // --- UGC Templates ---
  {
    id: 'ugc-01',
    title: 'Kitchen Review',
    description: 'A friendly face in a bright, modern kitchen. Perfect for food or home appliances.',
    category: 'UGC',
    previewImageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?auto=format&fit=crop&w=800&q=80',
    promptTemplate: 'A UGC-style video featuring a friendly presenter in a bright, modern kitchen. They are standing at a marble counter with {{PRODUCT_NAME}} clearly visible. The lighting is natural and inviting. The presenter is enthusiastic and genuine, talking directly to the camera about how {{PRODUCT_NAME}} has improved their cooking routine.',
    imageGenerationPrompt: 'A friendly presenter in a bright, modern kitchen with marble countertops and stainless steel appliances. Natural sunlight streams in. The presenter is smiling warmly at the camera, holding a product. High quality video still, 4k.',
    sceneDescription: 'A bright, modern kitchen with marble countertops and stainless steel appliances. Clean, domestic setting.',
    ugcAction: 'Standing at the counter, smiling warmly at the camera, occasionally gesturing towards the product or countertop.',
    type: 'video',
  },
  {
    id: 'ugc-02',
    title: 'Living Room Chat',
    description: 'A relaxed, cozy vibe in a comfortable living room setting.',
    category: 'UGC',
    previewImageUrl: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?auto=format&fit=crop&w=800&q=80',
    promptTemplate: 'A casual and relatable UGC video shot in a cozy living room. The presenter is sitting comfortably on a sofa with a soft throw blanket. {{PRODUCT_NAME}} is on the coffee table in front of them. The tone is conversational and honest, like a friend giving a recommendation.',
    imageGenerationPrompt: 'A cozy living room scene with a person sitting on a plush sofa. Warm lighting, soft textures, books on shelves in background. The person looks relaxed and is talking to the camera. 4k video still.',
    sceneDescription: 'A cozy living room with a plush sofa, soft throw blanket, and warm ambient lighting.',
    ugcAction: 'Sitting comfortably on the sofa, leaning forward slightly to talk to the camera like a friend.',
    type: 'video',
  },
  {
    id: 'ugc-03',
    title: 'Car Interior',
    description: 'Casual, on-the-go commentary from the passenger seat.',
    category: 'UGC',
    previewImageUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=800&q=80',
    promptTemplate: 'A UGC video filmed inside a parked car during the day. The presenter is in the driver or passenger seat, speaking candidly to their phone camera. {{PRODUCT_NAME}} is held up for a close-up. The vibe is spontaneous, authentic, and "real life".',
    imageGenerationPrompt: 'Interior shot of a modern car during the day. A person is sitting in the front seat, holding a product up to the camera lens. Natural daylight coming through the windows. Authentic vlog style. 4k video still.',
    sceneDescription: 'Inside a parked modern car during the day, with natural light coming through the windows.',
    ugcAction: "Sitting in the driver's seat, holding the phone camera selfie-style and gesturing with the free hand.",
    type: 'video',
  },
  {
    id: 'ugc-04',
    title: 'Gym Session',
    description: 'High energy and motivation in a fitness setting.',
    category: 'UGC',
    previewImageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
    promptTemplate: 'An energetic UGC video set in a gym. The presenter is wearing workout gear and looks motivated. They are taking a break from their workout to talk about {{PRODUCT_NAME}}. The background shows gym equipment. The energy is high, inspiring, and fitness-focused.',
    imageGenerationPrompt: 'A person in workout gear standing in a gym with weights and equipment in the blurred background. They look sweaty but energized, holding a water bottle or product. Bright, cool lighting. Fitness influencer style. 4k video still.',
    sceneDescription: 'A gym setting with weights and equipment visible in the blurred background.',
    ugcAction: 'Standing in workout gear, wiping brow, looking energized and motivated.',
    type: 'video',
  },
];
